apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pinpoint-web.fullname" . }}
  labels:
{{ include "pinpoint-web.labels" . | indent 4 }}
type: Opaque
data:
  ADMIN_PASSWORD: {{ .Values.adminPassword | b64enc | quote }}
  JDBC_USERNAME: {{ .Values.jdbc.username | b64enc | quote }}
  JDBC_PASSWORD: {{ .Values.jdbc.password | b64enc | quote }}
  MAIL_SERVER_USERNAME: {{ .Values.mail.server.username | b64enc | quote }}
  MAIL_SERVER_PASSWORD: {{ .Values.mail.server.password | b64enc | quote }}