version: "3.6"

services:
  pinpoint-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PINPOINT_VERSION=${PINPOINT_VERSION}

    container_name: "${PINPOINT_WEB_NAME}"
    image: "pinpointdocker/pinpoint-web:${PINPOINT_VERSION}"

    restart: always
    expose:
      - "8080"
      - "9997"
    ports:
      - "9997:9997"
      - "${WEB_PAGE_PORT:-8080}:8080"
    environment:
      - JAVA_OPTS="-Dspring.profiles.active=${SPRING_PROFILES},batch"
      - SPRING_PROFILES=${SPRING_PROFILES}
      - CLUSTER_ENABLE=${CLUSTER_ENABLE}
      - CLUSTER_ZOOKEEPER_ADDRESS=${CLUSTER_ZOOKEEPER_ADDRESS}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ANALYTICS=${ANALYTICS}
      - HBASE_HOST=${HBASE_HOST}
      - HBASE_PORT=${HBASE_PORT}
      - DEBUG_LEVEL=${WEB_DEBUG_LEVEL}
      - CONFIG_SHOW_APPLICATIONSTAT=${CONFIG_SHOW_APPLICATIONSTAT}
      - BATCH_ENABLE=${BATCH_ENABLE}
      - BATCH_SERVER_IP=${BATCH_SERVER_IP}
      - BATCH_FLINK_SERVER=${BATCH_FLINK_SERVER}
      - JDBC_DRIVER=${JDBC_DRIVER}
      - JDBC_URL=${JDBC_URL}
      - JDBC_USERNAME=${JDBC_USERNAME}
      - JDBC_PASSWORD=${JDBC_PASSWORD}
      - MAIL_SERVER_URL=${MAIL_SERVER_URL}
      - MAIL_SERVER_PORT=${MAIL_SERVER_PORT}
      - MAIL_SERVER_USERNAME=${MAIL_SERVER_USERNAME}
      - MAIL_SERVER_PASSWORD=${MAIL_SERVER_PASSWORD}
      - MAIL_SENDER_ADDRESS=${MAIL_SENDER_ADDRESS}
      - MAIL_TRANSPORT_PROTOCOL=${MAIL_TRANSPORT_PROTOCOL}
      - MAIL_SMTP_PORT=${MAIL_SMTP_PORT}
      - MAIL_SMTP_AUTH=${MAIL_SMTP_AUTH}
      - MAIL_SMTP_STARTTLS_ENABLE=${MAIL_SMTP_STARTTLS_ENABLE}
      - MAIL_SMTP_STARTTLS_REQUIRED=${MAIL_SMTP_STARTTLS_REQUIRED}
      - MAIL_DEBUG=${MAIL_DEBUG}
